### ISSUE TITLE
Plugin not updating values in background

### ISSUE THREAD

**Issue by deadlyknapsack** [honkmaster/homebridge-mi-flower-care#10]
I noticed that the plugin, regardless of the settings in config.json, is not getting value updates to Homebridge in the background. Is that deliberate? I am looking at the Home app on my iPad and the humidity percentage remains unchanged. The very second I open the Home app on my iPhone, the values are synced. Normally, that wouldn't be that big of a deal. However, I wanted to create an automation where a notification is sent when the humidity drops below a certain percentage. That becomes useless in terms of 'automation' when I have to get the percentage myself manually. 

Is this a bug or can you perhaps consider an enhancement on the plugin? I have about 15 Mi Flower modules and the idea was to have triggers when I need to water them... and now I am sad...

EDIT: I changed the interval to 10 seconds, just to test something and when I look at the logging of Homebridge, the plugin is posting the values correctly, every 10 seconds. Any idea why the Home app on my iPad is not getting the correct values updated from homebridge? 

EDIT2: I found this:

https://github.com/KhaosT/HAP-NodeJS/issues/543

Now, I am not a developer. But it seems to me that the plugin uses some kind of method to set the value, that doesn't trigger an update in iOS. I've read somewhere that you are busy with work, @honkmaster, but if you could have a look and see if that is easily implemented, it would mean the world to me. The reason I want this plugin to update in the background, is because I have an iPad on the wall, that has Home open constantly. If I have to keep opening and closing an app, in order to get an automation done, it defeats the purpose.

**Comment by honkmaster** [comment]
Could you try a recent development?

npm i -g --unsafe-perm honkmaster/homebridge-mi-flower-care#async

**Comment by honkmaster** [comment]
So, in my own experiment, automation in the background is working. I set a light (on / off), when lux falls below / rises above a certain level. Now it is your turn.

**Comment by deadlyknapsack** [comment]
> So, in my own experiment, automation in the background is working. I set a light (on / off), when lux falls below / rises above a certain level. Now it is your turn.

Brilliant. Works like a charm. Haven't tested it thoroughly yet, but I can see the values being updated without me having to be active in the Home app on my iPad or iPhone. To me, it is fixed. Thanks!

**Comment by honkmaster** [comment]
Great feedback. Thanks. Will merge and publish to NPM this evening.

**Comment by deadlyknapsack** [comment]
> Great feedback. Thanks. Will merge and publish to NPM this evening.

Should I change something in my setup? I have now installed the #async, but ideally would like to run the public version, no?

**Comment by honkmaster** [comment]
You can go back to the public version using:

`(sudo) npm install -g --unsafe-perm homebridge-mi-flower-care
`

Thanks again for testing.
