### ISSUE TITLE
Tolerance range for the minHumidityAlert

### ISSUE THREAD

**Issue by flobernd** [honkmaster/homebridge-mi-flower-care#14]
Hi there,

could you please implement a "tolerance range" for the `minHumidityAlert` value? The sensor data fluctuates a little which causes the alert to switch from "Off" to "On" and vice versa multiple times within a few minutes. This is somewhat annoying if you have Homekit notifications enabled.

A tolerance range from e.g. 1 with a `minHumidityAlert` of 30 could cause the alert to go "On", if the value is 29 and only go "Off" if the value is up to 31.

Best regards

**Comment by honkmaster** [comment]
I do not have time to provide / implement the requested changes. However, I am happy to accept a pull request.

**Comment by honkmaster** [comment]
No feedback and PR, close the issue for now.
