### ISSUE TITLE
MQTT feature built-in as homebridge-mi-hygrothermograph plugin

### ISSUE THREAD

**Issue by robotsflo** [honkmaster/homebridge-mi-flower-care#15]
Hi, 

Can you add the same MQTT Feature as "homebridge-mi-hygrothermograph" plugin ? 

You can visit  :
[https://github.com/hannseman/homebridge-mi-hygrothermograph#mqtt
](url)

Thanks a lot,

**Comment by honkmaster** [comment]
I do not have time to provide / implement the requested changes. However, I am happy to accept a pull request.

**Comment by honkmaster** [comment]
No feedback and PR, close the issue for now.
