### ISSUE TITLE
Feature Request: Disable Attribute

### ISSUE THREAD

**Issue by JangoBritt** [honkmaster/homebridge-mi-flower-care#17]
Hi!

Would it be an easy change, to allow the plugin to choose from the config.json to disable any of the elements not wanted in HomeKit? like Temperature, for example?

"DisableAttributes" : ["Temperature","Illumination"],

I've got three plants in the garden, for example, that are all giving me the same temperature reading, and it's not really adding any value to my already crowded collection of tiles.

**Comment by honkmaster** [comment]
Feel free to add a PR.

**Comment by JangoBritt** [comment]
I'm afraid I'm being quite cheeky with this request, because I've never used GitHub for development before.

I have experience with JavaScript, but not in Node.js, and not with GitHub. I could try, but not sure where to start. lol

**Comment by JangoBritt** [comment]
Would this do it? What would happen if it wasn't added to the JSON? If the Service isn't created, do subsequent calls to the variables cause the script to crash, or should every operation to the disabled service be validated inside a check of the config?

    if (config.DisabledAttributes.Temperature = null ) {
        this.tempService = new Service.TemperatureSensor(this.name);
        this.tempService.getCharacteristic(Characteristic.CurrentTemperature)
            .on('get', this.getCurrentTemperature.bind(this));
        this.tempService.getCharacteristic(Characteristic.StatusLowBattery)
            .on('get', this.getStatusLowBattery.bind(this));
        this.tempService.getCharacteristic(Characteristic.StatusActive)
            .on('get', this.getStatusActive.bind(this));
    }

**Comment by honkmaster** [comment]
No feedback and PR, close the issue for now.
