### ISSUE TITLE
one icon for temperature and humidity

### ISSUE THREAD

**Issue by skop1986** [honkmaster/homebridge-mi-flower-care#18]
is it possible to make the humidity displayed inside the temperature icon as it is done here?
![IMG_6413](https://user-images.githubusercontent.com/38746202/57855726-08826680-77f4-11e9-9ae3-5a256082c7b2.PNG)

**Comment by tonyduanesmith** [comment]
This will happen with iOS13

The tile you will see
![IMG_3379](https://user-images.githubusercontent.com/4118506/61769074-126eaa00-ade1-11e9-9b07-3ca94b7d6867.png)

When clicked into the tile
![IMG_3380](https://user-images.githubusercontent.com/4118506/61769096-1f8b9900-ade1-11e9-8bec-dd7c4e18a971.png)

**Comment by skop1986** [comment]
I already know, thanks.
