### ISSUE TITLE
Stop reading data after few days

### ISSUE THREAD

**Issue by Martvvliet** [honkmaster/homebridge-mi-flower-care#21]
Hi,
The plugin works fine for 1-3 days but then it stops working. It just keeps the same values. After a homebridge restart it works again. All the other plugins work fine.
Do you happen to know what this could be.
Also, is it possible to add some minor filtering of the received values, as it sometimes reads a crap value. Just an median filter would be nice :) thanks for the cool plugin :)

**Comment by souimanga** [comment]
Hi, same problems :)

**Comment by mattiasottosson** [comment]
I have the same problem. Logs show the following:

`noble warning: unknown handle 64 disconnected!
RangeError: Index out of range
at checkOffset (buffer.js:977:11)
at Uint8Array.Buffer.readUInt16LE (buffer.js:1023:5)
at Hci.onSocketData (/usr/local/lib/node_modules/homebridge-mi-flower-care/node_modules/noble/lib/hci-socket/hci.js:464:18)
at emitOne (events.js:116:13)
at BluetoothHciSocket.emit (events.js:211:7)
`

**Comment by souimanga** [comment]
Up up up

**Comment by honkmaster** [comment]
I have one instance running now more than 7 months without any issues or reading missing. Thus I con not reproduce the issue.
