### ISSUE TITLE
Running as sudo on startup via systemctl

### ISSUE THREAD

**Issue by niccolospa** [honkmaster/homebridge-mi-flower-care#3]
I'm using homebridge on a RPi and using this guide https://timleland.com/setup-homebridge-to-start-on-bootup/ I made homebridge running in background. The problem is that I don't know how to run it with root privilegies as the flower-care plugin requires. Can someone help me?

**Comment by honkmaster** [comment]
First idea: In homebridge.service you have to change the user to root. However, I am not running HB this way and I can not provide help for specific installations.
