### ISSUE TITLE
Update to work with  Node 12.13.1 LTS

### ISSUE THREAD

**Issue by BobbySlope** [honkmaster/homebridge-mi-flower-care#30]
Please update the plugin to work with  Node 12.13.1 LTS

**Comment by honkmaster** [comment]
Feel free to submit a pull request.

**Comment by BitsAndFlows** [comment]
@honkmaster - Did now a pull request, but i'm unsure, if its placed correctly...? https://github.com/lucavb/homebridge-mi-flora/pulls

**Comment by honkmaster** [comment]
Wrong place. Here is the correct one:
https://github.com/honkmaster/homebridge-mi-flower-care/pulls

**Comment by NathanAMiller** [comment]
its not work on 10.x either

**Comment by BitsAndFlows** [comment]
Check out [https://github.com/Martvvliet/homebridge-mi-flora-filtered](https://github.com/Martvvliet/homebridge-mi-flora-filtered). After last Update it works for me with HOOBS (which has Node 12.13.1) :-).

**Comment by Sungamm** [comment]
> 
> 
> Check out https://github.com/Martvvliet/homebridge-mi-flora-filtered. After last Update it works for me with HOOBS (which has Node 12.13.1) :-).

Hi, are you sure. In the NPM description they stated clear node 9.xx is necessary.

**Comment by BitsAndFlows** [comment]
> Hi, are you sure. In the NPM description they stated clear node 9.xx is necessary.

Yes, it's running on my HOOBS.

**Comment by Sungamm** [comment]
> 
> 
> > Hi, are you sure. In the NPM description they stated clear node 9.xx is necessary.
> 
> Yes, it's running on my HOOBS.

Thank you! Your are right and it is a great tipp! I installed the recommended version and it works with Node LTS. Thank you! :-)

**Comment by honkmaster** [comment]
Just update the submodules to support Node >= 10.
