### ISSUE TITLE
New Feature:Soil quality

### ISSUE THREAD

**Issue by boreder13** [honkmaster/homebridge-mi-flower-care#32]
Nutriant readings would be very helpful. Sensor is already able to read that data

**Comment by honkmaster** [comment]
This is already integrated, you have to use the elgato Eve app as this property is not shown in Apple Home.
![14B7BF5E-71D3-46CE-A314-89EC80619A6B](https://user-images.githubusercontent.com/1380397/84562052-9c08cc80-ad51-11ea-8c1d-cbb1e20997d5.png)
