### ISSUE TITLE
Support for Xiaomi flower pot model:	HHCCPOT002

### ISSUE THREAD

**Issue by andreasfrank** [honkmaster/homebridge-mi-flower-care#36]
Could you please implement  support for the Xiaomi flower pot. 
Decription: https://www.xiaomitoday.com/xiaomi-smart-flower-pot-flora-review/

Thx

**Comment by honkmaster** [comment]
I have no flower pot and can not test if the underlying library (node-mi-flora) supports this device. Sorry.
