### ISSUE TITLE
Node.js Version	v14.15.0 not supported

### ISSUE THREAD

**Issue by bondskin** [honkmaster/homebridge-mi-flower-care#37]
Hi,

Upgrading node.js on my Raspberry Pi to 14.15.0 makes homebridge to stop working as this plugin is failing

**Comment by vitaliy-kozlov** [comment]
same issue, any suggestions?

**Comment by honkmaster** [comment]
Hi @bondskin @vitaliy-kozlov. Back then, I fixed the non-functioning plugin from lucabv and added some functions. However, a major update (as required) is beyond my scope of knowledge and time to familiarise myself with. Sorry.

**Comment by honkmaster** [comment]
I recently did a fresh install of Homebridge with v16.17.0. Here, the plugin is working without issues.
