### ISSUE TITLE
hcitool doesn't work on my new system (Ubuntu 21.04 w/Intel AX200), will this plugin ever use bluetoothctl?

### ISSUE THREAD

**Issue by x5nder** [honkmaster/homebridge-mi-flower-care#42]
Since hcitool has been deprecated for quite a few years now, would you ever consider rewriting this plugin to use bluetoothctl instead of hcitool? Or are there any workarounds? I've tried finding ways to get hcitool to work, but no dice ("Set scan parameters failed: Input/output error").

**Comment by honkmaster** [comment]
No, that is beyond my capacity.
