### ISSUE TITLE
node.js 16.x not supported

### ISSUE THREAD

**Issue by bondskin** [honkmaster/homebridge-mi-flower-care#45]
Plugin is not running anymore with HB under node.js 16.13.0

**Comment by Walker-SW** [comment]
Agree - just upgraded and plug-in is no longer working.
Would be great if there will be a fix

**Comment by sercontri** [comment]
Good morning, I am also interested in implementing in Homebridge and from what I read it is no longer operational with the new updates. Hopefully we'll have an update one day. Thanks also for the work. Could someone help me anyway to get the MAC out of my flower care? Thanks!

**Comment by Walker-SW** [comment]
I use the app Mac Finder on Android to discover Bluetooth Devices.
The flower care devices show up with C4 at the beginning (at least mine) but I also get the name Flower care displayed.

**Comment by sercontri** [comment]
Thank you very much, hopefully the plugin can be used again.

**Comment by honkmaster** [comment]
Hi @Walker-SW @sercontri. Back then, I fixed the non-functioning plugin from lucabv and added some functions. However, a major update (as required) is beyond my scope of knowledge and time to familiarise myself with. Sorry.

**Comment by Walker-SW** [comment]
Hopefully there will be someone able to fix.
I love the plug-in and did not find any other solution so far...

**Comment by bondskin** [comment]
Hi @Walker-SW , you may want to try https://github.com/oretman/homebridge-mi-flora-care

**Comment by Walker-SW** [comment]
Hi all, 
installed [moifort](https://github.com/moifort) /
[homebridge-xiaomi-plant-monitor](https://github.com/moifort/homebridge-xiaomi-plant-monitor)
and this plugin works just fine with node.js 16.x
The only problem is, that it only support humidity but that is what I only need :)

**Comment by honkmaster** [comment]
I recently did a fresh install of Homebridge with v16.17.0. Here, the plugin is working without issues.
