### ISSUE TITLE
Graphics on eve app

### ISSUE THREAD

**Issue by sorriso93** [honkmaster/homebridge-mi-flower-care#5]
Hello, just curiosity. You know the reason why lux and fertility has no graph in the app?

**Comment by honkmaster** [comment]
You mean in the elgato app? If so, Eve does not support history for this data types.

**Comment by sorriso93** [comment]
Correct... so assuming to change data type in the plugin it's possible to have history data and graph also for the lux and fertility (first one is a number as temperature, second one is a percentage as moisture...)?

**Comment by honkmaster** [comment]
First temp is only possible -100 to 100, moisture 0 to 100. These ranges do not fit. For lux, it is an official supported type by apple, elgato and / or apple need to do the work.
