### ISSUE TITLE
Elevated privileges problem

### ISSUE THREAD

**Issue by septeven** [honkmaster/homebridge-mi-flower-care#8]
Hi there,
I didn't figure out how to make homebridge running with elevated privileges. 
Would you mind helping on this ?

Thanks

**Comment by netRunner0** [comment]
Ap

**Comment by netRunner0** [comment]
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)

**Comment by netRunner0** [comment]
https://github.com/weathernews/WxBeacon-node/wiki/Raspberry-Pi-3でWxBeaconを受信する
